# Generated by Django 6.1 on 2026-08-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0007_deliveryevent_foldercoverage_message_thread_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="prompt_line_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="message",
            name="prompt_line_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
