# Generated by Django 6.1 on 2026-08-26 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emails", "0007_deliveryevent_foldercoverage_message_thread_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("product_docs", models.TextField(blank=True, default="")),
                ("campaign_target", models.TextField(blank=True, default="")),
                ("booking_link", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lead_id", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("first_name", models.CharField(blank=True, default="", max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                ("company", models.CharField(blank=True, default="", max_length=200)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("website", models.CharField(blank=True, default="", max_length=500)),
                ("linkedin_url", models.CharField(blank=True, default="", max_length=500)),
                ("profile_text", models.TextField(blank=True, default="")),
                ("profile_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Suppression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("suppressed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Ready to Email", "Ready"),
                            ("Emailed", "Emailed"),
                            ("Completed", "Completed"),
                            ("Unsubscribed", "Unsubscribed"),
                        ],
                        default="Ready to Email",
                        max_length=32,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("converted", "Converted"),
                            ("not_interested", "Not Interested"),
                            ("wrong_fit", "Wrong Fit"),
                            ("no_budget", "No Budget"),
                            ("has_solution", "Has Solution"),
                            ("bad_timing", "Bad Timing"),
                            ("unresponsive", "Unresponsive"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("qualified_at", models.DateTimeField(blank=True, null=True)),
                ("email_subject", models.CharField(blank=True, default="", max_length=500)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("chat_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deals", to="leads.campaign"
                    ),
                ),
                (
                    "mailbox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="emails.mailbox",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="emails.thread",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deals", to="leads.lead"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["state"], name="deal_state_idx")],
                "constraints": [models.UniqueConstraint(fields=("lead", "campaign"), name="unique_deal_per_campaign")],
            },
        ),
    ]
