# Generated by Django 6.1 on 2026-08-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="state",
            field=models.CharField(
                choices=[
                    ("Ready to Email", "Ready"),
                    ("Emailed", "Emailed"),
                    ("Completed", "Completed"),
                    ("Unsubscribed", "Unsubscribed"),
                    ("Undeliverable", "Undeliverable"),
                ],
                default="Ready to Email",
                max_length=32,
            ),
        ),
    ]
